version: '3'

services:
  web:
    build: .
    # below is the code for the development server
    # command: python /code/manage.py runserver 0.0.0.0:8000
    # below is the code for the gunicorn production server
    command: gunicorn journal_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000